import os
import json
import logging
import re
from datetime import datetime, timedelta
from typing import Dict, Any, List

logger = logging.getLogger(__name__)

CACHE_PATH = os.path.join(os.path.dirname(__file__), "..", "state", "fo_universe_cache.json")

NSE_INDEX_DERIVATIVES = [
    {"symbol": "NIFTY", "ticker": "^NSEI", "lot_size": 25, "strike_step": 50.0, "is_index": True},
    {"symbol": "BANKNIFTY", "ticker": "^NSEBANK", "lot_size": 15, "strike_step": 100.0, "is_index": True},
    {"symbol": "FINNIFTY", "ticker": "NIFTY_FIN_SERVICE.NS", "lot_size": 25, "strike_step": 50.0, "is_index": True},
    {"symbol": "MIDCPNIFTY", "ticker": "NIFTY_MID_SELECT.NS", "lot_size": 50, "strike_step": 25.0, "is_index": True},
    {"symbol": "NIFTYNXT50", "ticker": "^NSMIDCP", "lot_size": 10, "strike_step": 100.0, "is_index": True},
]

# Complete Active NSE F&O Universe (180+ Stocks) with standard Lot Sizes & Sectors
ALL_NSE_FO_STOCKS = [
    # Mega Caps & Nifty 50
    {"symbol": "RELIANCE", "ticker": "RELIANCE.NS", "lot_size": 250, "strike_step": 20.0, "sector": "ENERGY"},
    {"symbol": "TCS", "ticker": "TCS.NS", "lot_size": 175, "strike_step": 50.0, "sector": "IT"},
    {"symbol": "INFY", "ticker": "INFY.NS", "lot_size": 300, "strike_step": 20.0, "sector": "IT"},
    {"symbol": "HDFCBANK", "ticker": "HDFCBANK.NS", "lot_size": 550, "strike_step": 20.0, "sector": "BANK"},
    {"symbol": "ICICIBANK", "ticker": "ICICIBANK.NS", "lot_size": 700, "strike_step": 10.0, "sector": "BANK"},
    {"symbol": "SBIN", "ticker": "SBIN.NS", "lot_size": 750, "strike_step": 10.0, "sector": "BANK"},
    {"symbol": "AXISBANK", "ticker": "AXISBANK.NS", "lot_size": 625, "strike_step": 10.0, "sector": "BANK"},
    {"symbol": "KOTAKBANK", "ticker": "KOTAKBANK.NS", "lot_size": 400, "strike_step": 20.0, "sector": "BANK"},
    {"symbol": "LT", "ticker": "LT.NS", "lot_size": 150, "strike_step": 50.0, "sector": "INFRA"},
    {"symbol": "ITC", "ticker": "ITC.NS", "lot_size": 1600, "strike_step": 5.0, "sector": "FMCG"},
    {"symbol": "HINDUNILVR", "ticker": "HINDUNILVR.NS", "lot_size": 300, "strike_step": 25.0, "sector": "FMCG"},
    {"symbol": "BHARTIARTL", "ticker": "BHARTIARTL.NS", "lot_size": 475, "strike_step": 20.0, "sector": "TELECOM"},
    {"symbol": "BAJFINANCE", "ticker": "BAJFINANCE.NS", "lot_size": 125, "strike_step": 100.0, "sector": "FINANCE"},
    {"symbol": "BAJAJFINSV", "ticker": "BAJAJFINSV.NS", "lot_size": 500, "strike_step": 25.0, "sector": "FINANCE"},
    {"symbol": "TATAMOTORS", "ticker": "TATAMOTORS.NS", "lot_size": 700, "strike_step": 10.0, "sector": "AUTO"},
    {"symbol": "MARUTI", "ticker": "MARUTI.NS", "lot_size": 50, "strike_step": 100.0, "sector": "AUTO"},
    {"symbol": "TATASTEEL", "ticker": "TATASTEEL.NS", "lot_size": 5500, "strike_step": 2.5, "sector": "METAL"},
    {"symbol": "HINDALCO", "ticker": "HINDALCO.NS", "lot_size": 700, "strike_step": 10.0, "sector": "METAL"},
    {"symbol": "JSWSTEEL", "ticker": "JSWSTEEL.NS", "lot_size": 675, "strike_step": 10.0, "sector": "METAL"},
    {"symbol": "SUNPHARMA", "ticker": "SUNPHARMA.NS", "lot_size": 350, "strike_step": 20.0, "sector": "PHARMA"},
    {"symbol": "CIPLA", "ticker": "CIPLA.NS", "lot_size": 325, "strike_step": 20.0, "sector": "PHARMA"},
    {"symbol": "DRREDDY", "ticker": "DRREDDY.NS", "lot_size": 125, "strike_step": 50.0, "sector": "PHARMA"},
    {"symbol": "TITAN", "ticker": "TITAN.NS", "lot_size": 175, "strike_step": 50.0, "sector": "CONSUMER"},
    {"symbol": "ASIANPAINT", "ticker": "ASIANPAINT.NS", "lot_size": 200, "strike_step": 25.0, "sector": "CONSUMER"},
    {"symbol": "NESTLEIND", "ticker": "NESTLEIND.NS", "lot_size": 25, "strike_step": 25.0, "sector": "FMCG"},
    {"symbol": "WIPRO", "ticker": "WIPRO.NS", "lot_size": 1500, "strike_step": 5.0, "sector": "IT"},
    {"symbol": "HCLTECH", "ticker": "HCLTECH.NS", "lot_size": 350, "strike_step": 20.0, "sector": "IT"},
    {"symbol": "NTPC", "ticker": "NTPC.NS", "lot_size": 1500, "strike_step": 5.0, "sector": "ENERGY"},
    {"symbol": "POWERGRID", "ticker": "POWERGRID.NS", "lot_size": 1800, "strike_step": 5.0, "sector": "ENERGY"},
    {"symbol": "ONGC", "ticker": "ONGC.NS", "lot_size": 1925, "strike_step": 2.5, "sector": "ENERGY"},
    {"symbol": "COALINDIA", "ticker": "COALINDIA.NS", "lot_size": 2100, "strike_step": 5.0, "sector": "ENERGY"},
    {"symbol": "ADANIENT", "ticker": "ADANIENT.NS", "lot_size": 300, "strike_step": 25.0, "sector": "DIVERSIFIED"},
    {"symbol": "ADANIPORTS", "ticker": "ADANIPORTS.NS", "lot_size": 400, "strike_step": 20.0, "sector": "INFRA"},
    {"symbol": "ULTRACEMCO", "ticker": "ULTRACEMCO.NS", "lot_size": 50, "strike_step": 100.0, "sector": "INFRA"},
    {"symbol": "GRASIM", "ticker": "GRASIM.NS", "lot_size": 250, "strike_step": 25.0, "sector": "INFRA"},
    {"symbol": "INDUSINDBK", "ticker": "INDUSINDBK.NS", "lot_size": 500, "strike_step": 20.0, "sector": "BANK"},
    {"symbol": "HAL", "ticker": "HAL.NS", "lot_size": 150, "strike_step": 100.0, "sector": "INFRA"},
    {"symbol": "BEL", "ticker": "BEL.NS", "lot_size": 2900, "strike_step": 5.0, "sector": "INFRA"},
    {"symbol": "BHEL", "ticker": "BHEL.NS", "lot_size": 4350, "strike_step": 2.0, "sector": "INFRA"},
    {"symbol": "SIEMENS", "ticker": "SIEMENS.NS", "lot_size": 125, "strike_step": 100.0, "sector": "INFRA"},
    {"symbol": "ABB", "ticker": "ABB.NS", "lot_size": 125, "strike_step": 100.0, "sector": "INFRA"},
    {"symbol": "POLYCAB", "ticker": "POLYCAB.NS", "lot_size": 125, "strike_step": 100.0, "sector": "INFRA"},
    {"symbol": "M&M", "ticker": "M&M.NS", "lot_size": 350, "strike_step": 20.0, "sector": "AUTO"},
    {"symbol": "EICHERMOT", "ticker": "EICHERMOT.NS", "lot_size": 175, "strike_step": 50.0, "sector": "AUTO"},
    {"symbol": "HEROMOTOCO", "ticker": "HEROMOTOCO.NS", "lot_size": 150, "strike_step": 50.0, "sector": "AUTO"},
    {"symbol": "ZOMATO", "ticker": "ZOMATO.NS", "lot_size": 3500, "strike_step": 2.0, "sector": "FMCG"},
    {"symbol": "VEDL", "ticker": "VEDL.NS", "lot_size": 2800, "strike_step": 5.0, "sector": "METAL"},
    {"symbol": "RECLTD", "ticker": "RECLTD.NS", "lot_size": 2200, "strike_step": 5.0, "sector": "FINANCE"},
    {"symbol": "PFC", "ticker": "PFC.NS", "lot_size": 2700, "strike_step": 5.0, "sector": "FINANCE"},
    {"symbol": "TRENT", "ticker": "TRENT.NS", "lot_size": 350, "strike_step": 25.0, "sector": "FMCG"},
    {"symbol": "SHREECEM", "ticker": "SHREECEM.NS", "lot_size": 25, "strike_step": 200.0, "sector": "INFRA"},
    {"symbol": "BANDHANBNK", "ticker": "BANDHANBNK.NS", "lot_size": 1800, "strike_step": 5.0, "sector": "BANK"},
    {"symbol": "PNB", "ticker": "PNB.NS", "lot_size": 8000, "strike_step": 2.0, "sector": "BANK"},
    {"symbol": "CANBK", "ticker": "CANBK.NS", "lot_size": 4500, "strike_step": 2.0, "sector": "BANK"},
    {"symbol": "BANKBARODA", "ticker": "BANKBARODA.NS", "lot_size": 4350, "strike_step": 2.0, "sector": "BANK"},
    {"symbol": "TECHM", "ticker": "TECHM.NS", "lot_size": 600, "strike_step": 10.0, "sector": "IT"},
    {"symbol": "MPHASIS", "ticker": "MPHASIS.NS", "lot_size": 175, "strike_step": 25.0, "sector": "IT"},
    {"symbol": "LTIM", "ticker": "LTIM.NS", "lot_size": 150, "strike_step": 50.0, "sector": "IT"},
    {"symbol": "PERSISTENT", "ticker": "PERSISTENT.NS", "lot_size": 125, "strike_step": 50.0, "sector": "IT"},
    {"symbol": "MOTHERSON", "ticker": "MOTHERSON.NS", "lot_size": 5000, "strike_step": 2.0, "sector": "AUTO"},
    {"symbol": "BOSCHLTD", "ticker": "BOSCHLTD.NS", "lot_size": 15, "strike_step": 500.0, "sector": "AUTO"},
    {"symbol": "TVSMOTOR", "ticker": "TVSMOTOR.NS", "lot_size": 350, "strike_step": 25.0, "sector": "AUTO"},
    {"symbol": "BAJAJ-AUTO", "ticker": "BAJAJ-AUTO.NS", "lot_size": 75, "strike_step": 100.0, "sector": "AUTO"},
    {"symbol": "ESCORTS", "ticker": "ESCORTS.NS", "lot_size": 175, "strike_step": 50.0, "sector": "AUTO"},
    {"symbol": "ASHOKLEY", "ticker": "ASHOKLEY.NS", "lot_size": 5000, "strike_step": 2.5, "sector": "AUTO"},
    {"symbol": "APOLLOTYRE", "ticker": "APOLLOTYRE.NS", "lot_size": 1700, "strike_step": 5.0, "sector": "AUTO"},
    {"symbol": "BHARATFORG", "ticker": "BHARATFORG.NS", "lot_size": 500, "strike_step": 20.0, "sector": "AUTO"},
    {"symbol": "MRF", "ticker": "MRF.NS", "lot_size": 5, "strike_step": 500.0, "sector": "AUTO"},
    {"symbol": "PAYTM", "ticker": "PAYTM.NS", "lot_size": 2000, "strike_step": 5.0, "sector": "FINANCE"},
    {"symbol": "NYKAA", "ticker": "NYKAA.NS", "lot_size": 4000, "strike_step": 2.0, "sector": "FMCG"},
    {"symbol": "DELHIVERY", "ticker": "DELHIVERY.NS", "lot_size": 2250, "strike_step": 5.0, "sector": "INFRA"},
    {"symbol": "SAIL", "ticker": "SAIL.NS", "lot_size": 4500, "strike_step": 2.0, "sector": "METAL"},
    {"symbol": "NMDC", "ticker": "NMDC.NS", "lot_size": 3750, "strike_step": 2.0, "sector": "METAL"},
    {"symbol": "NATIONALUM", "ticker": "NATIONALUM.NS", "lot_size": 3750, "strike_step": 2.5, "sector": "METAL"},
    {"symbol": "JINDALSTEL", "ticker": "JINDALSTEL.NS", "lot_size": 625, "strike_step": 10.0, "sector": "METAL"},
    {"symbol": "APLAPOLLO", "ticker": "APLAPOLLO.NS", "lot_size": 350, "strike_step": 20.0, "sector": "METAL"},
    {"symbol": "IRFC", "ticker": "IRFC.NS", "lot_size": 4350, "strike_step": 2.0, "sector": "FINANCE"},
    {"symbol": "IRCTC", "ticker": "IRCTC.NS", "lot_size": 875, "strike_step": 10.0, "sector": "FMCG"},
    {"symbol": "CONCOR", "ticker": "CONCOR.NS", "lot_size": 1000, "strike_step": 10.0, "sector": "INFRA"},
    {"symbol": "PIDILITIND", "ticker": "PIDILITIND.NS", "lot_size": 350, "strike_step": 20.0, "sector": "CHEMICAL"},
    {"symbol": "BERGEPAINT", "ticker": "BERGEPAINT.NS", "lot_size": 1100, "strike_step": 5.0, "sector": "CHEMICAL"},
    {"symbol": "UPL", "ticker": "UPL.NS", "lot_size": 1300, "strike_step": 5.0, "sector": "CHEMICAL"},
    {"symbol": "PIIND", "ticker": "PIIND.NS", "lot_size": 250, "strike_step": 50.0, "sector": "CHEMICAL"},
    {"symbol": "SRF", "ticker": "SRF.NS", "lot_size": 375, "strike_step": 25.0, "sector": "CHEMICAL"},
    {"symbol": "NAVINFLUOR", "ticker": "NAVINFLUOR.NS", "lot_size": 150, "strike_step": 50.0, "sector": "CHEMICAL"},
    {"symbol": "AARTIIND", "ticker": "AARTIIND.NS", "lot_size": 1000, "strike_step": 10.0, "sector": "CHEMICAL"},
    {"symbol": "DEEPAKNTR", "ticker": "DEEPAKNTR.NS", "lot_size": 300, "strike_step": 25.0, "sector": "CHEMICAL"},
    {"symbol": "TATACHEM", "ticker": "TATACHEM.NS", "lot_size": 550, "strike_step": 10.0, "sector": "CHEMICAL"},
    {"symbol": "COROMANDEL", "ticker": "COROMANDEL.NS", "lot_size": 350, "strike_step": 20.0, "sector": "CHEMICAL"},
    {"symbol": "GNFC", "ticker": "GNFC.NS", "lot_size": 1300, "strike_step": 5.0, "sector": "CHEMICAL"},
    {"symbol": "CHAMBLFERT", "ticker": "CHAMBLFERT.NS", "lot_size": 1500, "strike_step": 5.0, "sector": "CHEMICAL"},
    {"symbol": "DMART", "ticker": "DMART.NS", "lot_size": 175, "strike_step": 50.0, "sector": "FMCG"},
    {"symbol": "MUTHOOTFIN", "ticker": "MUTHOOTFIN.NS", "lot_size": 400, "strike_step": 20.0, "sector": "FINANCE"},
    {"symbol": "CHOLAFIN", "ticker": "CHOLAFIN.NS", "lot_size": 750, "strike_step": 10.0, "sector": "FINANCE"},
    {"symbol": "SBILIFE", "ticker": "SBILIFE.NS", "lot_size": 750, "strike_step": 10.0, "sector": "FINANCE"},
    {"symbol": "HDFCLIFE", "ticker": "HDFCLIFE.NS", "lot_size": 1100, "strike_step": 5.0, "sector": "FINANCE"},
    {"symbol": "ICICIGI", "ticker": "ICICIGI.NS", "lot_size": 500, "strike_step": 10.0, "sector": "FINANCE"},
    {"symbol": "LICI", "ticker": "LICI.NS", "lot_size": 700, "strike_step": 10.0, "sector": "FINANCE"},
    {"symbol": "SHRIRAMFIN", "ticker": "SHRIRAMFIN.NS", "lot_size": 300, "strike_step": 25.0, "sector": "FINANCE"},
    {"symbol": "M&MFIN", "ticker": "M&MFIN.NS", "lot_size": 2000, "strike_step": 5.0, "sector": "FINANCE"},
    {"symbol": "MANAPPURAM", "ticker": "MANAPPURAM.NS", "lot_size": 3000, "strike_step": 2.5, "sector": "FINANCE"},
    {"symbol": "LICHSGFIN", "ticker": "LICHSGFIN.NS", "lot_size": 1000, "strike_step": 10.0, "sector": "FINANCE"},
    {"symbol": "CANFINHOME", "ticker": "CANFINHOME.NS", "lot_size": 975, "strike_step": 10.0, "sector": "FINANCE"},
    {"symbol": "IDFCFIRSTB", "ticker": "IDFCFIRSTB.NS", "lot_size": 7500, "strike_step": 1.0, "sector": "BANK"},
    {"symbol": "FEDERALBNK", "ticker": "FEDERALBNK.NS", "lot_size": 5000, "strike_step": 2.0, "sector": "BANK"},
    {"symbol": "AUBANK", "ticker": "AUBANK.NS", "lot_size": 1000, "strike_step": 10.0, "sector": "BANK"},
    {"symbol": "RBLBANK", "ticker": "RBLBANK.NS", "lot_size": 2500, "strike_step": 5.0, "sector": "BANK"},
    {"symbol": "ABFRL", "ticker": "ABFRL.NS", "lot_size": 2600, "strike_step": 5.0, "sector": "FMCG"},
    {"symbol": "BATAINDIA", "ticker": "BATAINDIA.NS", "lot_size": 375, "strike_step": 20.0, "sector": "FMCG"},
    {"symbol": "PAGEIND", "ticker": "PAGEIND.NS", "lot_size": 15, "strike_step": 500.0, "sector": "FMCG"},
    {"symbol": "DABUR", "ticker": "DABUR.NS", "lot_size": 1250, "strike_step": 5.0, "sector": "FMCG"},
    {"symbol": "MARICO", "ticker": "MARICO.NS", "lot_size": 1200, "strike_step": 5.0, "sector": "FMCG"},
    {"symbol": "GODREJCP", "ticker": "GODREJCP.NS", "lot_size": 500, "strike_step": 10.0, "sector": "FMCG"},
    {"symbol": "COLPAL", "ticker": "COLPAL.NS", "lot_size": 350, "strike_step": 25.0, "sector": "FMCG"},
    {"symbol": "BRITANNIA", "ticker": "BRITANNIA.NS", "lot_size": 125, "strike_step": 50.0, "sector": "FMCG"},
    {"symbol": "TATACONSUM", "ticker": "TATACONSUM.NS", "lot_size": 550, "strike_step": 10.0, "sector": "FMCG"},
    {"symbol": "VBL", "ticker": "VBL.NS", "lot_size": 750, "strike_step": 10.0, "sector": "FMCG"},
    {"symbol": "JUBLFOOD", "ticker": "JUBLFOOD.NS", "lot_size": 1250, "strike_step": 5.0, "sector": "FMCG"},
    {"symbol": "DEVYANI", "ticker": "DEVYANI.NS", "lot_size": 2500, "strike_step": 2.5, "sector": "FMCG"},
    {"symbol": "DIVISLAB", "ticker": "DIVISLAB.NS", "lot_size": 150, "strike_step": 50.0, "sector": "PHARMA"},
    {"symbol": "LUPIN", "ticker": "LUPIN.NS", "lot_size": 425, "strike_step": 20.0, "sector": "PHARMA"},
    {"symbol": "AUROPHARMA", "ticker": "AUROPHARMA.NS", "lot_size": 550, "strike_step": 10.0, "sector": "PHARMA"},
    {"symbol": "TORNTPHARM", "ticker": "TORNTPHARM.NS", "lot_size": 250, "strike_step": 25.0, "sector": "PHARMA"},
    {"symbol": "ALKEM", "ticker": "ALKEM.NS", "lot_size": 125, "strike_step": 50.0, "sector": "PHARMA"},
    {"symbol": "BIOCON", "ticker": "BIOCON.NS", "lot_size": 2500, "strike_step": 5.0, "sector": "PHARMA"},
    {"symbol": "IPCALAB", "ticker": "IPCALAB.NS", "lot_size": 650, "strike_step": 10.0, "sector": "PHARMA"},
    {"symbol": "ZYDUSLIFE", "ticker": "ZYDUSLIFE.NS", "lot_size": 900, "strike_step": 10.0, "sector": "PHARMA"},
    {"symbol": "GLENMARK", "ticker": "GLENMARK.NS", "lot_size": 725, "strike_step": 10.0, "sector": "PHARMA"},
    {"symbol": "LAURUSLABS", "ticker": "LAURUSLABS.NS", "lot_size": 1700, "strike_step": 5.0, "sector": "PHARMA"},
    {"symbol": "SYNGENE", "ticker": "SYNGENE.NS", "lot_size": 1000, "strike_step": 10.0, "sector": "PHARMA"},
    {"symbol": "APOLLOHOSP", "ticker": "APOLLOHOSP.NS", "lot_size": 125, "strike_step": 50.0, "sector": "PHARMA"},
    {"symbol": "FORTIS", "ticker": "FORTIS.NS", "lot_size": 1250, "strike_step": 5.0, "sector": "PHARMA"},
    {"symbol": "MAXHEALTH", "ticker": "MAXHEALTH.NS", "lot_size": 650, "strike_step": 10.0, "sector": "PHARMA"},
    {"symbol": "COFORGE", "ticker": "COFORGE.NS", "lot_size": 150, "strike_step": 50.0, "sector": "IT"},
    {"symbol": "OFSS", "ticker": "OFSS.NS", "lot_size": 100, "strike_step": 100.0, "sector": "IT"},
    {"symbol": "KPITTECH", "ticker": "KPITTECH.NS", "lot_size": 400, "strike_step": 20.0, "sector": "IT"},
    {"symbol": "LTTS", "ticker": "LTTS.NS", "lot_size": 100, "strike_step": 50.0, "sector": "IT"},
    {"symbol": "TATAELXSI", "ticker": "TATAELXSI.NS", "lot_size": 100, "strike_step": 50.0, "sector": "IT"},
    {"symbol": "PERSISTENT", "ticker": "PERSISTENT.NS", "lot_size": 125, "strike_step": 50.0, "sector": "IT"},
    {"symbol": "TATAPOWER", "ticker": "TATAPOWER.NS", "lot_size": 1350, "strike_step": 5.0, "sector": "ENERGY"},
    {"symbol": "ADANIGREEN", "ticker": "ADANIGREEN.NS", "lot_size": 300, "strike_step": 25.0, "sector": "ENERGY"},
    {"symbol": "ADANIPOWER", "ticker": "ADANIPOWER.NS", "lot_size": 875, "strike_step": 10.0, "sector": "ENERGY"},
    {"symbol": "ATGL", "ticker": "ATGL.NS", "lot_size": 675, "strike_step": 10.0, "sector": "ENERGY"},
    {"symbol": "IOC", "ticker": "IOC.NS", "lot_size": 4875, "strike_step": 2.5, "sector": "ENERGY"},
    {"symbol": "BPCL", "ticker": "BPCL.NS", "lot_size": 1800, "strike_step": 5.0, "sector": "ENERGY"},
    {"symbol": "HPCL", "ticker": "HPCL.NS", "lot_size": 1350, "strike_step": 5.0, "sector": "ENERGY"},
    {"symbol": "GAIL", "ticker": "GAIL.NS", "lot_size": 3250, "strike_step": 2.5, "sector": "ENERGY"},
    {"symbol": "PETRONET", "ticker": "PETRONET.NS", "lot_size": 3000, "strike_step": 2.5, "sector": "ENERGY"},
    {"symbol": "IGL", "ticker": "IGL.NS", "lot_size": 1375, "strike_step": 5.0, "sector": "ENERGY"},
    {"symbol": "MGL", "ticker": "MGL.NS", "lot_size": 400, "strike_step": 20.0, "sector": "ENERGY"},
    {"symbol": "GUJGASLTD", "ticker": "GUJGASLTD.NS", "lot_size": 1250, "strike_step": 5.0, "sector": "ENERGY"},
    {"symbol": "DLF", "ticker": "DLF.NS", "lot_size": 825, "strike_step": 10.0, "sector": "REALTY"},
    {"symbol": "GODREJPROP", "ticker": "GODREJPROP.NS", "lot_size": 225, "strike_step": 25.0, "sector": "REALTY"},
    {"symbol": "OBEROIRLTY", "ticker": "OBEROIRLTY.NS", "lot_size": 350, "strike_step": 20.0, "sector": "REALTY"},
    {"symbol": "PRESTIGE", "ticker": "PRESTIGE.NS", "lot_size": 400, "strike_step": 20.0, "sector": "REALTY"},
    {"symbol": "PHOENIXLTD", "ticker": "PHOENIXLTD.NS", "lot_size": 350, "strike_step": 20.0, "sector": "REALTY"},
    {"symbol": "BRIGADE", "ticker": "BRIGADE.NS", "lot_size": 500, "strike_step": 10.0, "sector": "REALTY"},
    {"symbol": "SOBHA", "ticker": "SOBHA.NS", "lot_size": 350, "strike_step": 20.0, "sector": "REALTY"},
    {"symbol": "ACC", "ticker": "ACC.NS", "lot_size": 300, "strike_step": 20.0, "sector": "INFRA"},
    {"symbol": "AMBUJACEM", "ticker": "AMBUJACEM.NS", "lot_size": 900, "strike_step": 5.0, "sector": "INFRA"},
    {"symbol": "DALBHARAT", "ticker": "DALBHARAT.NS", "lot_size": 250, "strike_step": 25.0, "sector": "INFRA"},
    {"symbol": "RAMCOCEM", "ticker": "RAMCOCEM.NS", "lot_size": 850, "strike_step": 10.0, "sector": "INFRA"},
    {"symbol": "INDIACEM", "ticker": "INDIACEM.NS", "lot_size": 2900, "strike_step": 2.5, "sector": "INFRA"},
    {"symbol": "GMRINFRA", "ticker": "GMRINFRA.NS", "lot_size": 5000, "strike_step": 1.0, "sector": "INFRA"},
    {"symbol": "NBCC", "ticker": "NBCC.NS", "lot_size": 4000, "strike_step": 1.0, "sector": "INFRA"},
    {"symbol": "RVNL", "ticker": "RVNL.NS", "lot_size": 1250, "strike_step": 5.0, "sector": "INFRA"},
    {"symbol": "IRCON", "ticker": "IRCON.NS", "lot_size": 2250, "strike_step": 2.5, "sector": "INFRA"},
    {"symbol": "PVRINOX", "ticker": "PVRINOX.NS", "lot_size": 400, "strike_step": 20.0, "sector": "MEDIA"},
    {"symbol": "SUNTV", "ticker": "SUNTV.NS", "lot_size": 1500, "strike_step": 5.0, "sector": "MEDIA"},
    {"symbol": "ZEEL", "ticker": "ZEEL.NS", "lot_size": 3000, "strike_step": 2.5, "sector": "MEDIA"},
    {"symbol": "EXIDEIND", "ticker": "EXIDEIND.NS", "lot_size": 1200, "strike_step": 5.0, "sector": "AUTO"},
    {"symbol": "AMARAJABAT", "ticker": "AMARAJABAT.NS", "lot_size": 600, "strike_step": 10.0, "sector": "AUTO"},
    {"symbol": "HAVELLS", "ticker": "HAVELLS.NS", "lot_size": 500, "strike_step": 20.0, "sector": "CONSUMER"},
    {"symbol": "CROMPTON", "ticker": "CROMPTON.NS", "lot_size": 1800, "strike_step": 5.0, "sector": "CONSUMER"},
    {"symbol": "VOLTAS", "ticker": "VOLTAS.NS", "lot_size": 600, "strike_step": 10.0, "sector": "CONSUMER"},
    {"symbol": "BLUESTARCO", "ticker": "BLUESTARCO.NS", "lot_size": 350, "strike_step": 20.0, "sector": "CONSUMER"},
    {"symbol": "ASTRAL", "ticker": "ASTRAL.NS", "lot_size": 275, "strike_step": 25.0, "sector": "INFRA"},
    {"symbol": "SUPREMEIND", "ticker": "SUPREMEIND.NS", "lot_size": 125, "strike_step": 50.0, "sector": "INFRA"},
    {"symbol": "KEI", "ticker": "KEI.NS", "lot_size": 125, "strike_step": 50.0, "sector": "INFRA"},
    {"symbol": "SUZLON", "ticker": "SUZLON.NS", "lot_size": 7500, "strike_step": 1.0, "sector": "ENERGY"},
    {"symbol": "CESC", "ticker": "CESC.NS", "lot_size": 3000, "strike_step": 2.5, "sector": "ENERGY"},
    {"symbol": "NHPC", "ticker": "NHPC.NS", "lot_size": 6000, "strike_step": 1.0, "sector": "ENERGY"},
    {"symbol": "SJVN", "ticker": "SJVN.NS", "lot_size": 4500, "strike_step": 2.0, "sector": "ENERGY"},
]

def _is_valid_symbol(symbol: str) -> bool:
    if not symbol or not isinstance(symbol, str):
        return False
    # Strict regex: alphanumeric, &, -, ^
    return bool(re.match(r"^[A-Za-z0-9&_\^\.\-]+$", symbol.strip()))

def get_fo_universe() -> Dict[str, Any]:
    valid_stocks = [
        s for s in ALL_NSE_FO_STOCKS
        if _is_valid_symbol(s["symbol"]) and _is_valid_symbol(s["ticker"])
    ]
    valid_indices = [
        idx for idx in NSE_INDEX_DERIVATIVES
        if _is_valid_symbol(idx["symbol"]) and _is_valid_symbol(idx["ticker"])
    ]
    universe = {
        "indices": valid_indices,
        "stocks": valid_stocks
    }
    try:
        os.makedirs(os.path.dirname(CACHE_PATH), exist_ok=True)
        with open(CACHE_PATH, "w", encoding="utf-8") as f:
            json.dump(universe, f, indent=2)
    except Exception as e:
        logger.warning(f"[FO Universe Loader] Cache save notice: {e}")
    return universe
